// session types
export const RECEIVE_AUTH_TOKEN = 'RECEIVE_AUTH_TOKEN';
export const RECEIVE_SESSION_LOADING = 'RECEIVE_SESSION_LOADING';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

// stream types
export const RECEIVE_STREAM = 'RECEIVE_STREAM';
export const RECEIVE_STREAM_LOADING = 'RECEIVE_STREAM_LOADING';
export const RECEIVE_STREAM_CONSTRAINTS = 'RECEIVE_STREAM_CONSTRAINTS';

// message types
export const EXCHANGE = "EXCHANGE";
export const REMOVE_USER = "REMOVE_USER";
