// session types
export const RECEIVE_AUTH_TOKEN = 'RECEIVE_AUTH_TOKEN';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';
export const RECEIVE_SESSION_LOADING = 'RECEIVE_SESSION_LOADING';
export const RECEIVE_SESSION_ERROR = 'RECEIVE_SESSION_ERROR';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

// stream types
export const RECEIVE_STREAM = 'RECEIVE_STREAM';
export const REMOVE_STREAM = 'REMOVE_STREAM';
export const END_STREAM = 'END_STREAM';
export const RECEIVE_PEER_CONNECTION = 'RECEIVE_PEER_CONNECTION';
export const RECEIVE_PARTICIPANT = 'RECEIVE_PARTICIPANT';
export const RECEIVE_FULL_SCREEN = 'RECEIVE_FULL_SCREEN';
export const RECEIVE_STREAM_LOADING = 'RECEIVE_STREAM_LOADING';
export const RECEIVE_OFFER_STATUS = 'RECEIVE_OFFER_STATUS';
export const RECEIVE_POLITE_STATUS = 'RECEIVE_POLITE_STATUS';

// message types
export const REQUEST_CALL = 'REQUEST_CALL';
export const ACCEPT_CALL = 'ACCEPT_CALL';
export const JOIN_CALL = 'JOIN_CALL';
export const EXCHANGE = "EXCHANGE";

// user types
export const RECEIVE_USER = "RECEIVE_USER";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const RECEIVE_USER_LOADING = "RECEIVE_USER_LOADING";

// global types
export const RECEIVE_GLOBAL_ERROR = 'RECEIVE_GLOBAL_ERROR';
export const REMOVE_GLOBAL_ERROR = 'REMOVE_GLOBAL_ERROR';
