// session types
export const RECEIVE_AUTH_TOKEN = 'RECEIVE_AUTH_TOKEN';
export const RECEIVE_SESSION_LOADING = 'RECEIVE_SESSION_LOADING';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

// stream types
export const RECEIVE_STREAM = 'RECEIVE_STREAM';
export const RECEIVE_PEER_CONNECTION = 'RECEIVE_PEER_CONNECTION';
export const RECEIVE_PARTICIPANT = 'RECEIVE_PARTICIPANT';
export const RECEIVE_STREAM_LOADING = 'RECEIVE_STREAM_LOADING';

// message types
export const OFFER = "OFFER";
export const ANSWER = "ANSWER";
export const EXCHANGE = "EXCHANGE";
